// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PricingEngine.Infrastructure.Data;

#nullable disable

namespace PricingEngine.Infrastructure.Migrations
{
    [DbContext(typeof(PricingEngineDbContext))]
    [Migration("20260603063005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PricingEngine.Domain.Entities.ProductConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode", "ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("ix_product_configs_product_key");

                    b.ToTable("product_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000000"),
                            ConfigKey = "tariff_rate",
                            ConfigValue = "0.0018",
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductCode = "HOME_BASIC"
                        },
                        new
                        {
                            Id = new Guid("a1000002-0000-0000-0000-000000000000"),
                            ConfigKey = "fixed_fee",
                            ConfigValue = "25.00",
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductCode = "HOME_BASIC"
                        },
                        new
                        {
                            Id = new Guid("a1000003-0000-0000-0000-000000000000"),
                            ConfigKey = "tax_rate",
                            ConfigValue = "0.12",
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductCode = "HOME_BASIC"
                        },
                        new
                        {
                            Id = new Guid("a1000004-0000-0000-0000-000000000000"),
                            ConfigKey = "installment_fee_2x",
                            ConfigValue = "0.015",
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductCode = "HOME_BASIC"
                        },
                        new
                        {
                            Id = new Guid("a1000005-0000-0000-0000-000000000000"),
                            ConfigKey = "installment_fee_4x",
                            ConfigValue = "0.030",
                            EffectiveFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductCode = "HOME_BASIC"
                        });
                });

            modelBuilder.Entity("PricingEngine.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("Fees")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("InputDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_data");

                    b.Property<string>("InstallmentPlansJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("installment_plans");

                    b.Property<decimal>("NetPremium")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_quotes_created_at");

                    b.HasIndex("ProductCode")
                        .HasDatabaseName("ix_quotes_product_code");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("PricingEngine.Infrastructure.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "RetryCount")
                        .HasDatabaseName("ix_outbox_unprocessed");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("PricingEngine.Infrastructure.Entities.QuoteAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("ix_audit_quote_id");

                    b.ToTable("quote_audit_log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
